version: '3.8'

services:
  tablo-crawler:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env.example
    volumes:
      - ./src:/app/src