# Workflow for Fuel Advisor Bot CI/CD
name: Fuel Advisor Bot CI

on:
  push:
    branches: [main]
    paths:
      - 'apps/fuel-advisor-bot/**'
      - 'packages/shared-config/**'
      - 'packages/shared-lib/**'

  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/app-ci.yml
    with:
      app-name: fuel-advisor-bot