name: Build and Push Tablo Crawler

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/tablo-crawler/**'

jobs:
  build:
    uses: ./.github/workflows/app-ci.yml
    with:
      app-name: tablo-crawler