name: Build and Push Tablo Crawler

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/tablo-crawler/**'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/app-ci.yml
    permissions:
      contents: read
      packages: write
    with:
      app-name: tablo-crawler