# Workflow for Tablo Crawler CI/CD
name: Tablo Crawler CI

on:
  push:
    branches: [main]
    paths:
      - 'apps/tablo-crawler/**'
      - 'packages/shared-config/**'
      - 'packages/shared-lib/**'

  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/app-ci.yml
    with:
      app-name: tablo-crawler